name: deploy
on:
  workflow_dispatch:
  push:
    branches: ['main']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: NPM Cache
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install
    - name: Build site
      shell: bash
      run: echo "Complete"
    - name: deploy
      shell: bash
      env:
        GH_NAME: ${{ secrets.NAME }}
        GH_EMAIL: ${{ secrets.EMAIL }}
        AUTO_DEPLOY_TOKEN: ${{ secrets.AUTO_DEPLOY_TOKEN }}
      run: |
        cd dist
        git init
        git add .
        git -c user.name=$GH_NAME -c user.email=$GH_EMAIL commit -m "Auto Deployment"
        git push -f -q "https://orbitgw-bot:$AUTO_DEPLOY_TOKEN@github.com/blog-orbitgw/blog-orbitgw.github.io" master
